# Default values for samba.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/servercontainers/samba
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

secretRefs:
  sambaCreds:
    name: samba-creds
    usernameKey: username
    passwordKey: password

service:
  type: NodePort
  nodePort: 31732
  port: 445

shareName: Media

resources:
  limits:
    cpu: 4000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 1Gi

# Additional volumes on the output Deployment definition.
volumes:
  - name: data-volume
    persistentVolumeClaim:
     claimName: main-storage

volumeMounts: 
  - name: data-volume
    mountPath: /smbshare