maintenance:
  namespace: sdost # why tf is this here?
  enabled: true
  title: Under Construction
  message: Site coming soon!
  bannerURL: https://raw.githubusercontent.com/jshethbright/k8s-agnes-terraform/main/values/maintenance/logo_full_transparent_colors.png

ingress:
  enabled: true
  className: traefik
  host: sdost.org
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  tls:
    enabled: true
    secretName: sdost-ingress-tls
