image:
  repository: ghcr.io/onedr0p/qbittorrent
  pullPolicy: IfNotPresent
qbitportforwardImage:
  repository: mjmeli/qbittorrent-port-forward-gluetun-server
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
qbitportforward:
  enabled: false
service:
  main:
    ports:
      main:
        port: 10095
  torrent:
    enabled: true
    ports:
      torrent:
        enabled: true
        port: 6881
        protocol: tcp
      torrentudp:
        enabled: true
        port: "{{ .Values.service.torrent.ports.torrent.port }}"
        protocol: udp
  gluetun:
    enabled: false
    type: ClusterIP
    ports:
      gluetun:
        enabled: true
        port: 8000
        targetPort: 8000
        protocol: http
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            # set the default port
            QBITTORRENT__PORT: "{{ .Values.service.main.ports.main.port }}"
            # stops users from bricking their chart from setting the ip to a random ip when its a container.
            QBT_Preferences__WebUI__Address: "*"
            # set port from gui.
            QBT_BitTorrent__Session__Port: "{{ .Values.service.torrent.ports.torrent.port }}"
            # legacy ini key
            # key deprecated https://github.com/qbittorrent/qBittorrent/issues/8324
            QBT_Preferences__Connection__PortRangeMin: "{{ .Values.service.torrent.ports.torrent.port }}"
  qbitportforward:
    enabled: false
    type: CronJob
    schedule: "*/1 * * * *"
    podSpec:
      restartPolicy: OnFailure
      containers:
        qbitportforward:
          primary: true
          enabled: true
          imageSelector: qbitportforwardImage
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            QBT_USERNAME: "{{ .Values.qbitportforward.QBT_USERNAME }}"
            QBT_PASSWORD: "{{ .Values.qbitportforward.QBT_PASSWORD }}"
            QBT_ADDR: '{{ printf "http://qbittorrent.agnes-apps.svc.cluster.local:%v" .Values.service.main.ports.main.port }}'
            GTN_ADDR: "http://qbittorrent-gluetun.agnes-apps.svc.cluster.local:8000"
          command: /usr/src/app/main.sh
persistence:
  config:
    enabled: true
    mountPath: "/config"
  media:
    enabled: true
    type: pvc
    mountPath: /storage
    dataSource:
      kind: "PersistentVolumeClaim"
portal:
  open:
    enabled: true
ingress:
  qbittorrent-ingress:
    expandObjectName: true
    enabled: true
    primary: true
    required: false
    ingressClassName: traefik
    targetSelector:
      main: main
    hosts:
      - host: torrent.jitarth.com
        paths:
          - path: /
            pathType: Prefix
    integrations:
      certManager:
        enabled: true
        certificateIssuer: letsencrypt-issuer
      traefik:
        enabled: false
