persistence:
  config:
    enabled: true
    mountPath: "/config"
  cache:
    enabled: true
    mountPath: "/cache"
    type: "emptyDir"
  transcode:
    enabled: true
    mountPath: "/config/transcodes"
    type: "emptyDir"
  media:
    enabled: true
    type: pvc
    mountPath: /storage
    dataSource:
      kind: "PersistentVolumeClaim"
      name: main-storage
    existingClaim: main-storage
resources:
  limits:
    cpu: 4000m
    memory: 4Gi
workload:
  main:
    replicas: 1
    podSpec:
      containers:
        main:
          resources:
            limits:
              gpu.intel.com/i915: 1
ingress:
  jellyfin-ingress:
    expandObjectName: true
    enabled: true
    primary: true
    required: false
    ingressClassName: traefik
    targetSelector:
      main: main
    hosts:
      - host: jellyfin.jitarth.com
        paths:
          - path: /
            pathType: Prefix
    integrations:
      certManager:
        enabled: true
        certificateIssuer: letsencrypt-issuer
      traefik:
        enabled: false
