persistence:
  config:
    enabled: true
    mountPath: "/config"
  cache:
    enabled: true
    mountPath: "/cache"
    type: "emptyDir"
  transcode:
    enabled: true
    mountPath: "/config/transcodes"
    type: "emptyDir"
resources:
  limits:
    cpu: 4000m
    memory: 4Gi
# workload:
#   main:
#     podSpec:
#       containers:
#         main:
#           resources:
#             limits:
#               intel.com/i915: 1
ingress:
  jellyfin-ingress:
    expandObjectName: true
    enabled: true
    primary: true
    required: false
    expandObjectName: false
    ingressClassName: traefik
    targetSelector:
      main: main
    hosts:
      - host: jellyfin.jitarth.com
        paths:
          - path: /
            pathType: Prefix
    integrations:
      certManager:
        enabled: true
        certificateIssuer: letsencrypt-issuer
      traefik:
        enabled: false
persistence:
  hostpath-vol:
    enabled: true
    type: hostPath
    mountPath: /storage
    hostPath: /var/mnt/mainpool/MainMedia
    hostPathType: DirectoryOrCreate