image:
  repository: ghcr.io/techno-tim/littlelink-server
  pullPolicy: IfNotPresent
  tag: latest@sha256:5b411f96dc72e08cd3efb89e76d0b49ef5627fffc8bce532068203f658381210
service:
  main:
    ports:
      main:
        port: 10040
        targetPort: 3000
littlelink:
  meta_title: "OST @ SD"
  meta_description: "Orchestral Soundtracks "
  meta_author: "OST @ SD"
  theme: "Dark"
  favicon_url: "https://scontent-lax3-2.cdninstagram.com/v/t51.2885-19/455733566_1883047095523619_7788321685861190662_n.jpg?stp=dst-jpg_s320x320&_nc_ht=scontent-lax3-2.cdninstagram.com&_nc_cat=111&_nc_ohc=iBLC0bxhLGIQ7kNvgEJEPiE&edm=AOQ1c0wBAAAA&ccb=7-5&oh=00_AYBNoONJfWSV4bN6Mf1jjmNi5ZUeRMTKaqWHF8et8zUCTw&oe=66DF0906&_nc_sid=8b3546"
  avatar_url: "https://scontent-lax3-2.cdninstagram.com/v/t51.2885-19/455733566_1883047095523619_7788321685861190662_n.jpg?stp=dst-jpg_s320x320&_nc_ht=scontent-lax3-2.cdninstagram.com&_nc_cat=111&_nc_ohc=iBLC0bxhLGIQ7kNvgEJEPiE&edm=AOQ1c0wBAAAA&ccb=7-5&oh=00_AYBNoONJfWSV4bN6Mf1jjmNi5ZUeRMTKaqWHF8et8zUCTw&oe=66DF0906&_nc_sid=8b3546"
  # avatar_2x_url: "https://pbs.twimg.com/profile_images/1286144221217316864/qiaskopb_400x400.jpg"
  avatar_alt: ""
  name: "OST @ SD"
  bio: "We are a community orchestra specializing in Anime and Video Game music."
  instagram: "https://www.instagram.com/ost.sd/"
  discord: "https://discord.gg/qGeyJPXU"
  youtube: ""
  twitch: ""
  twitter: ""
  kit: ""
  github: ""
  tiktok: ""
  footer: "Thanks for checking us out!"
portal:
  open:
    enabled: true
workload:
  main:
    strategy: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
    replicas: 2
    podSpec:
      containers:
        main:
          envFrom:
            - configMapRef:
                name: config
ingress:
  littlelink-ingress:
    expandObjectName: true
    enabled: true
    primary: true
    required: false
    ingressClassName: traefik
    targetSelector:
      main: main
    hosts:
      - host: links.sdost.org
        paths:
          - path: /
            pathType: Prefix
    integrations:
      certManager:
        enabled: true
        certificateIssuer: letsencrypt-issuer
      traefik:
        enabled: false