ingress:
  rdtclient-ingress:
    expandObjectName: true
    enabled: true
    primary: true
    required: false
    ingressClassName: traefik
    targetSelector:
      main: main
    hosts:
      - host: rdtclient.jitarth.com
        paths:
          - path: /
            pathType: Prefix
    integrations:
      certManager:
        enabled: true
        certificateIssuer: letsencrypt-issuer
      traefik:
        enabled: false
persistence:
  db:
    enabled: true
    mountPath: "/data/db"
  config:
    enabled: true
    targetSelector:
      aria2:
        aria2:
          mountPath: /config
  media:
    enabled: true
    type: pvc
    mountPath: /data/media
    dataSource:
      kind: "PersistentVolumeClaim"
  aria2-media:
    enabled: true
    type: pvc
    dataSource:
      kind: "PersistentVolumeClaim"
    targetSelector:
      aria2:
        aria2:
          mountPath: /data/media
workload:
  aria2:
    enabled: true
    type: Deployment
    strategy: RollingUpdate
    replicas: 1
    podSpec:
      containers:
        aria2:
          primary: true
          enabled: true
          imageSelector: aria2Image
          securityContext:
            readOnlyRootFilesystem: false
            runAsGroup: 0
            runAsNonRoot: false
            runAsUser: 0
          probes:
            liveness:
              enabled: true
              type: tcp
              port: "{{ .Values.service.aria2.ports.rpc.port }}"
            readiness:
              enabled: true
              type: tcp
              port: "{{ .Values.service.aria2.ports.rpc.port }}"
            startup:
              enabled: true
              type: tcp
              port: "{{ .Values.service.aria2.ports.rpc.port }}"
          env:
            RPC_PORT: "{{ .Values.service.aria2.ports.rpc.port }}"
            LISTEN_PORT: "{{ .Values.service.torrent.ports.torrent.port }}"
            RPC_SECRET: "{{ .Values.aria2.rpc_secret }}"
            DISK_CACHE: "{{ .Values.aria2.disk_cache }}"
            IPV6_MODE: false
            UPDATE_TRACKERS: "{{ .Values.aria2.update_trackers }}"
            CUSTOM_TRACKER_URL: "{{ .Values.aria2.custom_trackers_url }}"
resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 100m
    memory: 2Gi
