ingress:
  actual-ingress:
    expandObjectName: true
    enabled: true
    primary: true
    required: false
    ingressClassName: traefik
    targetSelector:
      main: main
    hosts:
      - host: actual.jitarth.com
        paths:
          - path: /
            pathType: Prefix
    integrations:
      certManager:
        enabled: true
        certificateIssuer: letsencrypt-issuer
      traefik:
        enabled: false
persistence:
  data:
    enabled: true
    mountPath: /data
portal:
  open:
    enabled: true